### ISSUE TITLE
missing html file or php file

### ISSUE THREAD

**Issue by blazebrown87221** [scratchfoundation/scratch-gui#9522]
### Expected Behavior

I should have access to the website (not scratch-www)

### Actual Behavior

GitHub 404

### Steps to Reproduce

1 go to https://scratchfoundation.github.io/scratch-gui/develop/

### System Details
not a problem

**Screenshots**

![image](https://github.com/scratchfoundation/scratch-gui/assets/96564866/743b6ea7-b294-4477-bee0-9efc40253610)

**Comment by mybearworld** [comment]
Remove the "/develop": https://scratchfoundation.github.io/scratch-gui/

**Comment by sumeet05xcaliber** [comment]
guys i am new to this project and i am not able to understand it , like the project is  made in a different way than the traditional way how we create a react app , can you please explain me like how to add something on to the website if i want to
for example if i want to have a section like intstruction to the rightmost side of the webpage how i can.
